# Generated by Django 5.1.6 on 2025-03-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_budget_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
