# Generated by Django 5.1.6 on 2025-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_budget_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='money',
            field=models.IntegerField(),
        ),
    ]
