# Generated by Django 5.1.6 on 2025-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_budget_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
