# Generated by Django 5.1.6 on 2025-03-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_budget_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='money',
            new_name='amount',
        ),
    ]
